version: '3.1'

services:
  mysql:
    image: mysql:latest
    volumes:
      - "./data/mysql:/var/lib/mysql"
    ports:
      - "33066:33060"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
